name: custom_builders
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: "^9.0.0"
  build: ^4.0.0
  custom_annotations:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_annotations
  flutter:
    sdk: flutter
  source_gen: ">=3.1.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
