name: shared_ui
description: App UI shared pkg
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  core:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: pkg/core
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.6.0
  custom_builders:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_builders
  # custom_lint: ^0.8.1  # Incompatible with riverpod_generator 4.x (analyzer 9 vs 8)
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  index_generator: ^4.0.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/licences/
    - assets/png/
    - assets/svg/
    - assets/translations/
    - google_fonts/
