name: authentication
description: An authentication pkg that used across projects
version: 1.0.0
# homepage: ''
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  core:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: pkg/core
  crypto: ^3.0.1
  firebase_auth: ^5.6.2
  flutter:
    sdk: flutter
  # Add if there is a special need for extra scopes etc.
  # google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  build_runner: ^2.6.0
  custom_builders:
    git:
      url: https://github.com/chaPe4ever/flutter
      ref: main
      path: builders/custom_builders
    # custom_lint: ^0.8.1  # Incompatible with riverpod_generator 4.x (analyzer 9 vs 8)
  custom_lint: ^0.7.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
